### ISSUE TITLE
tracing core module and node 0.11.15

### ISSUE THREAD

**Issue by mpal9000** [AndreasMadsen/trace#12]
Hi, the "tracing" core module has been removed from node v0.11.15

**Comment by AndreasMadsen** [comment]
Oh, yeah, that was supposed to happen eventually. @trevnorris what is the recommended alternative to the `tracing` module?

**Comment by trevnorris** [comment]
Nothing right now. Currently there is an undocumented way to tap into `AsyncWrap`'s internal mechanism, and left that way to module developers can experiment with the API so we can get feedback while figuring out the best API to use.

**Comment by AndreasMadsen** [comment]
@trevnorris Thanks for clarifying, I will try migrating to that API.

**Comment by AndreasMadsen** [comment]
@mpal9000 I'm working on. But unfortunately there is a few bugs in the new `AsyncWrap` interface. So for now you will have to stick to node 0.11.14.

**Comment by mpal9000** [comment]
All right, thank you!

**Comment by AndreasMadsen** [comment]
@mpal9000 node 0.11.15, 0.11.16 and iojs should now be supported. However it uses some really dirty hacks so I can't promise anything, but we will just have to take those issues as they appear. Node 0.11.14 is still supported using the old approach, so you can downgrade to that if you hit any major issues.

**Comment by mpal9000** [comment]
I'll let you know if I have any issues, thanks!
