### ISSUE TITLE
Memory usage with fs.createReadStream()

### ISSUE THREAD

**Issue by julien-f** [AndreasMadsen/trace#17]
```js
require('trace')

var stream = require('fs').createReadStream('huge file here')
stream.resume()
```

It seems that the entire file is loaded in memory.

**Comment by AndreasMadsen** [comment]
There doesn't appear to be any memory leaks, but there is an odd behaviour in the RSS part which usually comes from `new Buffer` allocations. I have no idea what it is about, `trace` doesn't change the behaviour of node in any of those areas.

**baseline**
![no-trace](https://cloud.githubusercontent.com/assets/505333/11955929/682a482a-a8b6-11e5-9c31-d0892707bb11.png)

**with trace**
![with-trace](https://cloud.githubusercontent.com/assets/505333/11955920/663c3c3a-a8b6-11e5-8e8c-ae82c2c54304.png)

**Comment by julien-f** [comment]
Side question: which tool are you using to analyse memory usage in Node?

**Comment by AndreasMadsen** [comment]
I just wrote something simple: https://github.com/AndreasMadsen/trace/commit/7e5496aca15b821a5e3306f58cd7d62255331c3e

maybe I will do a real module some day :D

**Comment by AndreasMadsen** [comment]
7b91e4a5487bf0b998b69465b4528747fc2ff510 should fix this. If you try it out (please do) be aware that you will need at least node version 5.2.0 for now. However I have been promised that the necessary node features will land soon in 4.x.

**Comment by AndreasMadsen** [comment]
I don't get why this is an issue. I suspect it might be a v8 bug in the gc, 7b91e4a5487bf0b998b69465b4528747fc2ff510 basically just moved the stack object into an id-map and does the memory management itself. For future reference I also tried using a WeekMap, so I din't have to use the gc destroy event, there was an improvement but not enough.

**WeakMap using handle object**
![4-weak-map](https://cloud.githubusercontent.com/assets/505333/12008115/f365ef98-ac26-11e5-839f-a5f43c908626.png)

**Map using uid and destructor event**
![5-fix](https://cloud.githubusercontent.com/assets/505333/12008117/f9b227a4-ac26-11e5-863f-6e67716cae97.png)

**Comment by AndreasMadsen** [comment]
Thanks for creating the issue. I really appreciate the time you use on `trace` and `stack-chain` :+1:

**Comment by julien-f** [comment]
Glad to help.

Thanks for your work :)
