### ISSUE TITLE
Getting "node::AsyncWrap::AsyncWrap init hook threw" error when using 2.0.2

### ISSUE THREAD

**Issue by saintedlama** [AndreasMadsen/trace#21]
After updating to 2.0.2 (from 2.0.1) I'm getting a `FATAL ERROR: node::AsyncWrap::AsyncWrap init hook threw` error when using trace.

Tested with node.js versions 4.2.3 and 4.2.4 on windows

**Comment by AndreasMadsen** [comment]
The tests parse, so I will need to testcase to debug this.

**Comment by AndreasMadsen** [comment]
Node 4.2.5 have been released. This is compatible with latest version of trace (2.2.1), thus should solve any issues.

**Comment by aleung** [comment]
@AndreasMadsen Which node.js 5.x version is compatible with trace 2.3.0? I'm using node 5.3.0 have the same issue.

**Comment by AndreasMadsen** [comment]
@aleung 2.3.0 is definitely compatible with 5.7.0

I tested on node 5.3.0 and it appears that npm installs `async-hook@1.3.0` (works with 5.7.0) as a trace dependency, where is should install `async-hook@1.2.0` (works with 5.3.0 to 5.6.x). The engine field is correctly specified, npm just don't use it for version selection.

The best I can suggests, is that you manually replace the `async-hook` with `async-hook@1.2.0`. If you have any better ideas please let me know.

_Your issue has very little todo with your issue. The error is very common when using async-wrap / async-hook,. But I understand the confusing. I've edited the first comment to notify others._

**Comment by AndreasMadsen** [comment]
Tacking issue: https://github.com/nodejs/LTS/issues/86
