### ISSUE TITLE
attempting to print the stack results in a TypeError

### ISSUE THREAD

**Issue by cdaringe** [AndreasMadsen/trace#23]
```
debug> repl
Press Ctrl + C to leave debug repl
> e = new Error('e')
{ handle: 6,
  type: 'error',
  className: 'Error',
  constructorFunction: { ref: 7 },
  protoObject: { ref: 8 },
  prototypeObject: { ref: 1 },
  properties:
   [ { name: 'stack', attributes: 2, propertyType: 3, ref: 1 },
     { name: 'message', attributes: 2, propertyType: 0, ref: 9 } ],
  text: 'Error: e' }
> e.stack
TypeError: Cannot read property 'slice' of undefined
```

**Comment by AndreasMadsen** [comment]
> node -e "require('trace'); console.log((new Error).stack)"

works for me, so does the manual input into the repl.

What version of node and trace are you using. If you have updated node please also update trace, even if the version of `trace` match its dependencies may have been updated.

**Comment by cdaringe** [comment]
interesting.  unable to replicate.  closing. will revisit if it comes up again!
