### ISSUE TITLE
Make it work again with 4.4.3 LTS again

### ISSUE THREAD

**Issue by FlorianLoch** [AndreasMadsen/trace#25]
According to the history of the project (and also the readme) I assume the module once worked fine with the 4.x branch of Node.js - so are there any plans to make it work with the LTS (again)?

**Comment by AndreasMadsen** [comment]
Yes, there are. see https://github.com/AndreasMadsen/trace/issues/24

You can bump the issue here: https://github.com/nodejs/LTS/issues/86 - if I'm really good I find the time to make a PR to node myself this weekend, but don't count on it.

**Comment by AndreasMadsen** [comment]
And in the mean time you can replace `async-hook` with version `1.2.0` and `trace` should work as expected.

**Comment by AndreasMadsen** [comment]
Node.js v4.5.0 is now available. This has the latest AsyncWrap API and thus `trace` should work out of the box.
