### ISSUE TITLE
Compatibility with node ^7.0

### ISSUE THREAD

**Issue by BartWaardenburg** [AndreasMadsen/trace#31]
When running this module with node ^7.0 `yarn` gives the following warning (`npm` ignores it and installs succesfully):

`error trace@2.3.3: The engine "node" is incompatible with this module. Expected version "^4.5 || ^6.0".`

**Comment by AndreasMadsen** [comment]
We are experiencing some issue in node.js, you can follow our progress at https://github.com/nodejs/node/pull/9467

If you are luck `trace` will still work, but it's not something that I can guarantee.

**Comment by AndreasMadsen** [comment]
Issue node.js issue (nodejs/node#9467) is now fixed, I have updated the engine requirements accordingly.
