### ISSUE TITLE
Conflict of stack-trace version with the one from clarify

### ISSUE THREAD

**Issue by Alexsey** [AndreasMadsen/trace#39]
After I have execute an `npm i` in a clear folder (without `package-lock.json` and `node_modules`) I have start obtaining the error right on the app start
```
F:\test\node_modules\trace\node_modules\stack-chain\index.js:10
    throw new Error('Conflicting version of stack-chain found');
    ^

Error: Conflicting version of stack-chain found
    at Object.<anonymous> (F:\test\node_modules\trace\node_modules\stack-chain\index.js:10:11)
    at Object.<anonymous> (F:\test\node_modules\trace\trace.js:3:15)
```

STR:
1. Create an empty folder
2. Execute in it `npm i clarify trace`
3. Create a file with code
```js
require('clarify')
require('trace')
```
4. Execute file

I'm posting this issue in `trace` repo, while probably it's the `clarify` that is needed to be updated, because update of `trace` has lead to this problem

npm: 5.5.1
node: 9.3.0

**Comment by AndreasMadsen** [comment]
Thanks, should be fixed now.
