### ISSUE TITLE
Add GitHub releases

### ISSUE THREAD

**Issue by ehmicky** [AndreasMadsen/trace#41]
First, thanks for this project, this is very helpful!

Would it be possible to `git tag` the versions, so that GitHub releases are automatically created? This is helpful when users are subscribing to this repository using a RSS reader. Thanks!

**Comment by AndreasMadsen** [comment]
I will try and do that in the future. However, I will properly forget.

**Comment by ehmicky** [comment]
Those projects could help you not forget: [https://github.com/webpro/release-it](release-it), [https://github.com/sindresorhus/np](https://github.com/sindresorhus/np) or [https://github.com/inikulin/publish-please](https://github.com/inikulin/publish-please)
