### ISSUE TITLE
Treating error.stack as immutable?

### ISSUE THREAD

**Issue by alcuadrado** [AndreasMadsen/trace#44]
Hi Andreas,

As you may have seen [here](https://github.com/nodejs/node/issues/11865#issuecomment-414725817) and [here](https://github.com/nodejs/node/issues/11865#issuecomment-414823718), if [this proposal](https://github.com/tc39/proposal-error-stacks) gets approved errors' stacks will be immutable. If that happens `trace` will need a redesign.

The main difference would be that the async-trace would have to be stored somewhere else, so printing a `trace`-enhanced stack trace will require special logic.

A default `uncaughtException` handler can be set by `trace` to print the complete errors in node, but special integrations with everything else will be needed. For example, [mocha](https://mochajs.org/) prints stack traces of tests that unexpectedly throw, and would need a `trace` integration to take advantage of it.

While this alternative design is not as cool as just adding `-r trace` in front of `node`, I think it's worth exploring if showing its usefulness can help [v8's error-creation hook](https://bugs.chromium.org/p/v8/issues/detail?id=7525) move forward and have a workable solution for async-traces.

**Comment by AndreasMadsen** [comment]
@alcuadrado From what I'm reading in the thread, it will still be possible to set `[[ErrorData]]` on `Error` construction. So that should be okay. Dealing with `uncaughtException` is going to be nasty, so I hope that won't be the case.

**Comment by alcuadrado** [comment]
I'm not that familiar with the last few versions of the EcmaScript standard, but [this comment](https://github.com/nodejs/node/issues/11865#issuecomment-414823718) says that the proposal will forbid modifying `[[ErrorData]]`.

But I read again the proposal, and if I understand correctly [this](https://tc39.github.io/proposal-error-stacks/#sec-set-error.prototype-stack) will let you assign `error.stack`, circumventing the immutability of `[[ErrorData]]`. If this is correct this issue can be ignored as `trace` could still work.
