### ISSUE TITLE
Support Bluebird coroutines

### ISSUE THREAD

**Issue by samcday** [AndreasMadsen/trace#6]
First up, really love this library + stack-chain! Awesome stuff. I investigated using it in an app I have, but unfortunately I ran into some issues. Here's my problem.

I'm not sure how familiar you are with ES6 generators when used with a promise library that supports them (q / bluebird / others). Basically, instead of CPS-style spaghetti or noisy promise handling code, you can do this:

```
var promise = require("bluebird");

var gogo = Promise.coroutine(function*() {
    yield someMethodThatReturnsAPromise();
    yield someOtherMethodThatAlsoReturnsAPromise();
    throw new Exception("Omg awesome!");
});

process.nextTick(gogo);
```

Essentially, it makes async code look synchronous again, and you can actually use try/catch to handle errors that come back from async oeprations. Awesome-sauce.

The problem is that this library follows all of these yielded promises through async ops and back again. As a result, the stack trace for the snippet of code above actually includes stack frames for every single yielded promise. This means that instead of seeing a clean stacktrace from when the co-routine was called up until the error was thrown, we instead see the calls to `someMethodThatReturnsAPromise` and `someOtherMethodThatAlsoReturnsAPromise` + any async operations they went through in the trace.

I tried to do some hacky insanity with `trace`. I added a mark + rewind feature that would snapshot the stack, and then reset the callsites back to the saved ones after each yielded promise was resolved, but there was a bunch of corner cases and it felt really ... wrong. I was wondering, since you wrote this library and have obviously thought through this stuff alot, if you had any ideas about how to handle this?

If this all sounds incoherent, let me know and I can craft up a proper test case for you to play with.

**Comment by AndreasMadsen** [comment]
I think we can finally close this after https://github.com/AndreasMadsen/async-hook/pull/2. It may not be exactly what you wanted, but I think what you want is best provided by a third party module that uses `stack-chain`.
